apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  refreshInterval: {{ .Values.secretStore.refreshInterval }}
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretStore.awsCredsSecretName }}
            key: access-key-id
          secretAccessKeySecretRef:
            name: {{ .Values.secretStore.awsCredsSecretName }}
            key: secret-access-key
